### PR TITLE
feat: refactor with typescript to support esm and cjs both

### PR DESCRIPTION
**Pull request by liuhanqu**
BREAKING CHANGE: Drop Node.js < 16 support

1. 使用 ts 重构
2. 使用 tshy 支持 esm 和 cjs
3. test 使用 test-runner (这里需要 node v18 版本)

## Summary by CodeRabbit

- **New Features**
  - Introduced `waitPort` function for asynchronously waiting for port availability.
  - Added comprehensive test cases for CLI tools and port detection.

- **Updates**
  - Updated Node.js versions in workflows to include the latest versions.
  - Enhanced `detectPort` function with improved parameter handling and versatility.

- **Bug Fixes**
  - None specified.

- **Chores**
  - Updated `.gitignore` to exclude `.tshy*` files and `dist/` directory.
  - Updated dependencies and scripts in `package.json`.
  - Configured ESLint for improved code quality and consistency.

- **Refactor**
  - Migrated to ES6 import syntax for better module management.

### CODE REVIEW

**Comment by fengmk2** [comment]
https://github.com/node-modules/detect-port/blob/master/.github/workflows/nodejs.yml#L18 这里去掉 14，加上 20 的测试环境

**Comment by liuhanqu** [comment]
想问下 waitPort 方法的使用场景是什么？
看了代码，没太 get 到

**Comment by fengmk2** [comment]
> 想问下 waitPort 方法的使用场景是什么？ 看了代码，没太 get 到

一直在尝试等待指定端口可用。

**Comment by fengmk2** [comment]
我重新基于你的分支 rebase 一下.

**Pull request closed without merging**
